In [ ]:
import gym

***Question: ***
What is the purpose of OpenAI gyms and how is it going to help us in our RL education?

**Answer:**
OpenAI gym is a toolkit to test RL algorithms on various environments. It is almost like a gym to train and test RL algortihms on agents to compare them against one another. It will help with our RL education because it will allow us to experiment with various RL algortihms to determine which one performs better in the various algorithms

In [ ]:
gym.envs.register(
    id='FrozenLakeNotSlippery-v0',
    entry_point='gym.envs.toy_text:FrozenLakeEnv',
    kwargs={'map_name' : '4x4', 'is_slippery': False},
    max_episode_steps=100,
    reward_threshold=0.74
)

In [ ]:
# Create the gridworld-like environment
env=gym.make('FrozenLakeNotSlippery-v0')
# Let's look at the model of the environment (i.e., P):
env.env.P
# Question: what is the data in this structure saying? Relate this to the course
# presentation of P

{0: {0: [(1.0, 0, 0.0, False)],
  1: [(1.0, 4, 0.0, False)],
  2: [(1.0, 1, 0.0, False)],
  3: [(1.0, 0, 0.0, False)]},
 1: {0: [(1.0, 0, 0.0, False)],
  1: [(1.0, 5, 0.0, True)],
  2: [(1.0, 2, 0.0, False)],
  3: [(1.0, 1, 0.0, False)]},
 2: {0: [(1.0, 1, 0.0, False)],
  1: [(1.0, 6, 0.0, False)],
  2: [(1.0, 3, 0.0, False)],
  3: [(1.0, 2, 0.0, False)]},
 3: {0: [(1.0, 2, 0.0, False)],
  1: [(1.0, 7, 0.0, True)],
  2: [(1.0, 3, 0.0, False)],
  3: [(1.0, 3, 0.0, False)]},
 4: {0: [(1.0, 4, 0.0, False)],
  1: [(1.0, 8, 0.0, False)],
  2: [(1.0, 5, 0.0, True)],
  3: [(1.0, 0, 0.0, False)]},
 5: {0: [(1.0, 5, 0, True)],
  1: [(1.0, 5, 0, True)],
  2: [(1.0, 5, 0, True)],
  3: [(1.0, 5, 0, True)]},
 6: {0: [(1.0, 5, 0.0, True)],
  1: [(1.0, 10, 0.0, False)],
  2: [(1.0, 7, 0.0, True)],
  3: [(1.0, 2, 0.0, False)]},
 7: {0: [(1.0, 7, 0, True)],
  1: [(1.0, 7, 0, True)],
  2: [(1.0, 7, 0, True)],
  3: [(1.0, 7, 0, True)]},
 8: {0: [(1.0, 8, 0.0, False)],
  1: [(1.0, 12, 0.0, True)],
  2: [(

***Question:*** what is the data in this structure saying? Relate this to the course
presentation of P

**Answer:**
In the course, P represnts the following probablistic function:
 P(s',r | s,a), which is the probablity of going into next state s' with reward
 r given being in state s and taking action a.

 The data structure env.env.P is showing us a dictionary with 16 values from
 0 to 15. each corresponding to being in state s in [0 to 15].

 Within each of the s values is another dictionary containing 4 tuples.
 Each tuple contains information corresponding to taking action 'a' while being in state 's'. Action 'a' can
 have a value between 0 to 3.

 Each tuple is of the following structure:

 [(probability of going into state s' given being in state s and taking action a,

 state s',

 reward r,

 boolean of whether done= true, meaning fell in Hole or acheive goal or done = false, meaning can keep on moving)]  


 In this case, the probability of going into state s' given being in state s and taking action a is always 1 because the "is_slippery" is set to False.

 From the openai gym wiki on github, the actions are as follows:

0	Move Left
1	Move Down
2	Move Right
3	Move Up





In [ ]:
# Now let's investigate the observation space (i.e., S using our nomenclature),
# and confirm we see it is a discrete space with 16 locations
print(env.observation_space)

Discrete(16)


In [ ]:
stateSpaceSize = env.observation_space.n
print(stateSpaceSize)

16


In [ ]:
# Now let's investigate the action space (i.e., A) for the agent->environment
# channel
print(env.action_space)

Discrete(4)


In [ ]:
# The gym environment has ...sample() functions that allow us to sample
# from the above spaces:
for g in range(1,10,1):
  print("sample from S:",env.observation_space.sample()," ... ","sample from A:",env.action_space.sample())



sample from S: 6  ...  sample from A: 1
sample from S: 5  ...  sample from A: 3
sample from S: 9  ...  sample from A: 3
sample from S: 15  ...  sample from A: 2
sample from S: 10  ...  sample from A: 2
sample from S: 11  ...  sample from A: 2
sample from S: 7  ...  sample from A: 0
sample from S: 9  ...  sample from A: 2
sample from S: 10  ...  sample from A: 0


In [ ]:
# The enviroment also provides a helper to render (visualize) the environment
env.reset()
env.render()


SFFF
FHFH
FFFH
HFFG


In [ ]:
# We can act as the agent, by selecting actions and stepping the environment
# through time to see its responses to our actions
env.reset()
exitCommand=False
while not(exitCommand):
  env.render()
  print("Enter the action as an integer from 0 to",env.action_space.n - 1," (or exit): ")
  userInput=input()
  if userInput=="exit":
    break
  action=int(userInput)
  (observation, reward, compute, probability) = env.step(action)
  print("--> The result of taking action",action,"is:")
  print("     S=",observation)
  print("     R=",reward)
  print("     p=",probability)

  env.render()



SFFF
FHFH
FFFH
HFFG
Enter the action as an integer from 0 to 3  (or exit): 
2
--> The result of taking action 2 is:
     S= 1
     R= 0.0
     p= {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Enter the action as an integer from 0 to 3  (or exit): 
3
--> The result of taking action 3 is:
     S= 1
     R= 0.0
     p= {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
Enter the action as an integer from 0 to 3  (or exit): 
1
--> The result of taking action 1 is:
     S= 5
     R= 0.0
     p= {'prob': 1.0}
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
Enter the action as an integer from 0 to 3  (or exit): 
exit


In [ ]:
# Question: draw a table indicating the correspondence between the action
# you input (a number) and the logic action performed.

from tabulate import tabulate

actions_logic = [[0,"Move Left"], [1, "Move Down"], [2, "Move Right"], [3, "Move Up"]]

print(tabulate(actions_logic, headers=['Action Number', 'Logic Action Performed']))

# Question: draw a table that illustrates what the symbols on the render image
# mean?

state_symbols = [["S","Start Point (Safe)"], ["F", "Frozen Surface (Safe)"]
                 , ["H", "Hole (Not Safe)"], ["G", "Goal (reach where the frisbee is located)"]]

print()
print("According to the OpenAI Gym website https://gym.openai.com/envs/FrozenLake-v0/")
print(tabulate(state_symbols, headers=['State Symbol', 'Meaning']))

# Question: Explain what the objective of the agent is in this environment?

print()
print()
print("The objective of the agent is to navigate through a lake to retrieve a frisbee.")
print("The lake is structured in a grid form with tiles of frozen surface (F) and")
print("tiles of holes (H). The agent starts at the starting tile (S) is the aim")
print("is to navigate through the tiles until reach the goal (G) tile which contains")
print("the frisbee. If the agent stands on hole (H) it falls into the water")
print("and cannot proceed with navigation.")

  Action Number  Logic Action Performed
---------------  ------------------------
              0  Move Left
              1  Move Down
              2  Move Right
              3  Move Up

According to the OpenAI Gym website https://gym.openai.com/envs/FrozenLake-v0/
State Symbol    Meaning
--------------  -----------------------------------------
S               Start Point (Safe)
F               Frozen Surface (Safe)
H               Hole (Not Safe)
G               Goal (reach where the frisbee is located)


The objective of the agent is to navigate through a lake to retrieve a frisbee.
The lake is structured in a grid form with tiles of frozen surface (F) and
tiles of holes (H). The agent starts at the starting tile (S) is the aim
is to navigate through the tiles until reach the goal (G) tile which contains
the frisbee. If the agent stands on hole (H) it falls into the water
and cannot proceed with navigation.


In [ ]:
# Practical: Code up an AI that will employ random action selection in order
# to drive the agent. Test this random action selection agent with the
# above environment (i.e., code up a loop as I did above, but instead
# of taking input from a human user, take it from the AI you coded).

env.reset()
exitCommand=False

observation=""
prev_observation="" # to hold information about the current state that the agent is in
while not(exitCommand):
  env.render()
  action=env.action_space.sample()

  if observation =="":
    prev_observation=0
  else:
    prev_observation=observation

  (observation, reward, compute, probability) = env.step(action)
  print("--> The result of taking action",action,"is:")
  print("     S=",observation)
  print("     R=",reward)
  print("     p=",probability)


  #get info about exitCommand (whether fell in hole or reached goal)
  exitCommand = env.env.P[prev_observation][action][0][3]
  env.render()



SFFF
FHFH
FFFH
HFFG
--> The result of taking action 2 is:
     S= 1
     R= 0.0
     p= {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
--> The result of taking action 2 is:
     S= 2
     R= 0.0
     p= {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
--> The result of taking action 3 is:
     S= 2
     R= 0.0
     p= {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
--> The result of taking action 3 is:
     S= 2
     R= 0.0
     p= {'prob': 1.0}
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
--> The result of taking action 2 is:
     S= 3
     R= 0.0
     p= {'prob': 1.0}
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
--> The result of taking action 0 is:
     S= 2
     R= 0.0
     p= {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
--> The result of taking action 0 is:
     S= 1
     R= 0.0
     p= {'prob': 1.0}
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
-

In [ ]:
import numpy as np

# Now towards dynamic programming. Note that env.env.P has the model
# of the environment.
#
# Question: How would you represent the agent's policy function and value function?
print("I would represent the agent's policy function and value funtion")
print("in a tabular format using numpy")



I would represent the agent's policy function and value funtion
in a tabular format using numpy


In [ ]:

# Practical: revise the above AI solver to use a policy function in which you
# code the random action selections in the policy function. Test this.



# policy function
def init_policy(env):

  #initiate policy to code the random action selections within it
  policy = np.zeros((env.observation_space.n))

  for i in range(env.observation_space.n):
    policy[i]=int(env.action_space.sample())
  return policy


env.reset()
exitCommand=False

observation=""
prev_observation="" # to hold information about the current state that the agent is in
policy=init_policy(env) #initiate the policy
while not(exitCommand):
  env.render()

  if observation =="":
    prev_observation=0
  else:
    prev_observation=observation

  #get action from initiated policy
  action = int(policy[prev_observation])

  (observation, reward, compute, probability) = env.step(action)
  print("--> The result of taking action",action,"is:")
  print("     S=",observation)
  print("     R=",reward)
  print("     p=",probability)


  #get info about exitCommand (whether fell in hole or reached goal)
  exitCommand = env.env.P[prev_observation][action][0][3]
  env.render()


Streaming output truncated to the last 5000 lines.
     R= 0.0
     p= {'prob': 1.0, 'TimeLimit.truncated': True}
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
--> The result of taking action 3 is:
     S= 1
     R= 0.0
     p= {'prob': 1.0, 'TimeLimit.truncated': True}
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
--> The result of taking action 3 is:
     S= 1
     R= 0.0
     p= {'prob': 1.0, 'TimeLimit.truncated': True}
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
--> The result of taking action 3 is:
     S= 1
     R= 0.0
     p= {'prob': 1.0, 'TimeLimit.truncated': True}
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
--> The result of taking action 3 is:
     S= 1
     R= 0.0
     p= {'prob': 1.0, 'TimeLimit.truncated': True}
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
--> The result of taking action 3 is:
     S= 1
     R= 0.0
     p= {'prob': 1.0, 'TimeLimit.truncated': True}
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
--> The

KeyboardInterrupt: ignored

In [ ]:
# Practical: Code the C-4 Policy Evaluation (Prediction) algorithm. You may use
# either the inplace or ping-pong buffer (as described in the lecture). Now
# randomly initialize your policy function, and compute its value function.
# Report your results: policy and value function. Ensure your prediction
# algo reports how many iterations it took.


# initialize policy function
def init_random_policy():
  # initiate policy as an equiprobable randomly initialized policy
  policy=np.ones([env.observation_space.n, env.action_space.n]) / env.action_space.n
  return policy

# initialize state value function
def init_state_value():
  # initialize state value function as 0 for all states
  V=np.zeros(env.observation_space.n)
  return V


#theta is threshold for accuracy
#gamma is discounting factor, this is epoisodic so can have gamma=1
def policy_eval(policy, env, theta, gamma):

  #initialize V(s) as zeroes
  V=init_state_value()
  v=0
  iterations=0
  while True:
    iterations+=1
    delta =0
    for s in range(env.observation_space.n):
      v=V[s]
      V[s]=0 # reset to 0 because will recalculate
      for a in range(env.action_space.n):
        for p, s_prime, r, exitCommand in env.env.P[s][a]:
          V[s] += (policy[s][a] * p * (r + (gamma*V[s_prime])))
      delta = max(delta, abs(v-V[s]))

    if delta < theta:
      break

  return V, iterations


policy = init_random_policy()
V=policy_eval(policy,env,0.0001,1)

print("The Value Function is: ")
print()
print(V[0])
print("The number of iterations is: ", V[1])

The Value Function is: 

[0.0024677  0.00411357 0.01075476 0.00420108 0.00388702 0.
 0.02615061 0.         0.013107   0.04856787 0.09386673 0.
 0.         0.08732907 0.30075702 0.        ]
The number of iterations is:  10


In [ ]:
# (Optional): Repeat the above for q.

# initialize state value function
def init_state_action_value():
  # initialize state value function as 0 for all states
  Q=np.zeros((env.observation_space.n, env.action_space.n))
  return Q

#theta is threshold for accuracy
#gamma is discounting factor, this is epoisodic so can have gamma=1
def policy_eval_q(policy, env, theta, gamma):

  #initialize Q(s) as zeroes
  Q=init_state_action_value()
  quit=0


  #initialize V(s) as zeroes
  V=init_state_value()
  iterations=0
  while True:
    delta =0
    iterations +=1
    for s in range(env.observation_space.n):
      for a in range(env.action_space.n):
        q=Q[s,a]
        Q[s,a]=0 # reset to 0 because will recalculate
        for p, s_prime, r, exitCommand in env.env.P[s][a]:
          Q[s,a] += p * (r + (gamma*V[s_prime]))
      delta = max(delta, abs(q-Q[s,a]))

      V[s]= np.sum(Q[s], axis=0)
    if delta < theta:
      break

  return Q, iterations


policy = init_random_policy()
Q=policy_eval_q(policy,env,0.0001,1)

print("The Value Action Function is: ")
print()
print(Q[0])
print("The number of iterations is: ", Q[1])


The Value Action Function is: 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
The number of iterations is:  1


In [ ]:
# Policy Improvement:
# Question: How would you use P and your value function to improve an arbitrary
# policy, pi, per Chapter 4?

***Question:*** How would you use P and your value function to improve an arbitrary
policy, pi, per Chapter 4?

*Answer:*
I would first use pi to select the actions, then I would select an action not in the detrmninistic policy and use P to calculate the action value function (q)for it.

Then, to evaluate whether this new action is better than the action in the detrminstic policy, I would compare the state value function of being in state s to the calculated action value function for the action not in the policy pi.

If q(s,new action based on new policy) >= v(s) based on old policy

Then, new policy >= old policy

Hence determine and improve the policy



In [ ]:
# Practical: Code the policy iteration process, and employ it to arrive at a
# policy that solves this problem. Show your testing results, and ensure
# it reports the number of iterations for each step: (a) overall policy
# iteration steps and (b) evaluation steps.

def policy_iteration(policy, env, theta, gamma):
  policy = init_random_policy()
  result_eval=policy_eval(policy, env, theta, gamma)
  policy_eval_iterations = result_eval[1]
  V=result_eval[0]
  #policy improvement
  #initialize Q(s) as zeroes
  Q=init_state_action_value()
  policy_stable=True
  for s in range(env.observation_space.n):

    #get  old_action from policy
    old_action= np.where(policy[s] == np.amax(policy[s]))[0][0]
    for a in range(env.action_space.n):
        for p, s_prime, r, exitCommand in env.env.P[s][a]:
          Q[s,a] += p * (r + (gamma*V[s_prime]))


    policy[s,np.where(Q[s] == np.amax(Q[s]))[0][0]] = 1
  print(policy)



policy_iteration(policy, env, 0.0001, 1)

[[0.25 0.25 1.   0.25]
 [0.25 0.25 1.   0.25]
 [0.25 1.   0.25 0.25]
 [1.   0.25 0.25 0.25]
 [0.25 1.   0.25 0.25]
 [1.   0.25 0.25 0.25]
 [0.25 1.   0.25 0.25]
 [1.   0.25 0.25 0.25]
 [0.25 0.25 1.   0.25]
 [0.25 0.25 1.   0.25]
 [0.25 1.   0.25 0.25]
 [1.   0.25 0.25 0.25]
 [1.   0.25 0.25 0.25]
 [0.25 0.25 1.   0.25]
 [0.25 0.25 1.   0.25]
 [1.   0.25 0.25 0.25]]


In [ ]:




# Practical: Code the value iteration process, and employ it to arrive at a
# policy that solves this problem. Show your testing results, reporting
# the iteration counts.

# Comment on the difference between the iterations required for policy vs
# value iteration.
#
# Optional: instead of the above environment, use the "slippery" Frozen Lake via
# env = gym.make("FrozenLake-v0")